---
# tasks file for apache

- name: Set apache variables
  ansible.builtin.set_fact:
    apache_package: "{{ 'apache2' if ansible_distribution in ['Ubuntu', 'Debian'] else 'httpd' }}"
    apache_service: "{{ 'apache2' if ansible_distribution in ['Ubuntu', 'Debian'] else 'httpd' }}"

- name: Install apache
  ansible.builtin.apt:
    name: "{{ apache_package }}"
    state: present
    update_cache: true

- name: Configure apache port
  ansible.builtin.template:
    src: apache.conf.j2
    dest: "/etc/{{ apache_package }}/ports.conf"
    mode: "0600"
  notify: Restart apache

- name: Replace <title> header in Apache default page
  ansible.builtin.lineinfile:
    path: /var/www/html/index.html
    regexp: '<title>.*</title>'
    line: '<title>{{ apache_message }}</title>'
    backup: true

- name: Ensure apache is running
  ansible.builtin.service:
    name: "{{ apache_service }}"
    state: started
    enabled: true
  check_mode: false
