apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: production
  labels:
    app: flask-app
    environment: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
      environment: production
  template:
    metadata:
      labels:
        app: flask-app
        environment: production
    spec:
      containers:
      - name: flask-app
        image: registry.gitlab.com/mephi-okr/hw8/flask-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 6088
        resources:
          limits:
            memory: "512Mi"
            cpu: "1000m"
          requests:
            memory: "256Mi"
            cpu: "500m"
      imagePullSecrets:
      - name: registry-auth