apiVersion: v1
kind: Service
metadata:
  name: flask-app
  namespace: production
  labels:
    app: flask-app
    environment: production
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 6088
  selector:
    app: flask-app
    environment: production