apiVersion: v1
kind: Service
metadata:
  name: flask-app
  namespace: staging
  labels:
    app: flask-app
    environment: staging
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 6088
  selector:
    app: flask-app
    environment: staging